# Site settings
title: Matthew Barber
email: quitesimplymatt@gmail.com
description: >-
  Personal website of Matthew Barber.
baseurl: "/"
url: "https://matthewbarber.io/"
twitter_username: whostolehonno
github_username: honno

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
sass:
  sass_dir: _sass
